when:
  - event: [pull_request,push]
    branch: [main, feature/*]

steps:
  - name: build
    image: node:latest
    commands:
      - echo "Installing dependencies..."
      - npm --prefix app install 
  - name: test
    image: node:latest
    commands:
      - echo "Running tests..."
      - npm --prefix app test
# build:
#   commands:

# docker:
#   when:
#     event:
#       - push
#     branch:
#       - main
#   secrets:
#     - DOCKER_USERNAME
#     - DOCKER_PASSWORD
#   commands:
#     - echo "Generating image version..."
#     - VERSION=$(date +'%Y%m%d%H%M%S')
#     - echo "VERSION=${VERSION}" > version.txt
#     - echo "Logging in to Docker Hub..."
#     - echo "$${DOCKER_PASSWORD}" | docker login -u "$${DOCKER_USERNAME}" --password-stdin
#     - echo "Building and pushing Docker image..."
#     - docker build -t "$${DOCKER_USERNAME}/my-node-app:$VERSION" .
#     - docker tag "$${DOCKER_USERNAME}/my-node-app:$VERSION" "$${DOCKER_USERNAME}/my-node-app:latest"
#     - docker push "$${DOCKER_USERNAME}/my-node-app:$VERSION"
#     - docker push "$${DOCKER_USERNAME}/my-node-app:latest"

# update_k8s:
#   when:
#     event:
#       - push
#     branch:
#       - main
#   secrets:
#     - DOCKER_USERNAME
#   commands:
#     - echo "Fetching image version..."
#     - VERSION=$(cat version.txt)
#     - echo "Updating Kubernetes spec file..."
#     - sed -i "s|image: ${DOCKER_USERNAME}/my-node-app:.*|image: ${DOCKER_USERNAME}/my-node-app:${VERSION}|" k8s/deployment.yaml
#     - git config --global user.email "ci-bot@example.com"
#     - git config --global user.name "Woodpecker CI Bot"
#     - git commit -am "Update Kubernetes spec with image version $VERSION"
#     - git push origin main
