when:
  - event: [push,pull_request]
    branch: main

steps:
  - name: build
    image: node:latest
    commands:
      - echo "Installing dependencies..."
      - npm --prefix app install 
  - name: test
    image: node:latest
    commands:
      - echo "Running jest tests..."
      - npm --prefix app test
  - name: build and push image
    image: woodpeckerci/plugin-kaniko
    settings:
      registry: "docker.io"  # Docker registry URL (can be Docker Hub or any other registry)
      repo: "docker.io/prateekjoshi2013/woodpecker-ci-demo"  # Your Docker image name
      dockerfile: "app/Dockerfile"  # Path to Dockerfile in the 'app' subfolder
      context: "app"  # Build context is the 'app' subfolder where your Dockerfile and app code are located
      username:
        from_secret: docker-username
      password:
        from_secret: docker-password

