when:
  - event: [push,pull_request]
    branch: main

steps:
  - name: build
    image: node:latest
    commands:
      - echo "Installing dependencies..."
      - npm --prefix app install 
  - name: test
    image: node:latest
    commands:
      - echo "Running jest tests..."
      - npm --prefix app test

  - name: build-and-push
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: docker.io/${CI_REPO_OWNER}/woodpecker-ci-demo
      dockerfile: app/Dockerfile
      context: app
      platforms: linux/amd64,linux/arm64/v8
      tag: next
      username:
        from_secret: docker-username
      password:
        from_secret: docker-password


