when:
  - event: [push,pull_request]
    branch: main

steps:
  - name: build
    image: node:latest
    commands:
      - echo "Installing dependencies..."
      - npm --prefix app install 
  - name: test
    image: node:latest
    commands:
      - echo "Running jest tests..."
      - npm --prefix app test
  - name: test
    image: plugins/kaniko
    settings:
      repo: prateekjoshi2013/woodpecker-ci-demo
      tags: latest,v1-${CI_COMMIT_SHA:0:8}
      dockerfile: app/Dockerfile
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
