when:
  - event: [push,pull_request]
    branch: main

steps:
  - name: build
    image: node:latest
    commands:
      - echo "Installing dependencies..."
      - npm --prefix app install 
  - name: test
    image: node:latest
    commands:
      - echo "Running jest tests..."
      - npm --prefix app test

  - name: build-and-push
    image: docker:dind
    privileged: true
    environment:
      DOCKER_USERNAME: from_secret:docker-username
      DOCKER_PASSWORD: from_secret:docker-password
    commands:
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - docker build -t "$DOCKER_USERNAME/woodpecker-ci-demo:latest" app/
      - docker push "$DOCKER_USERNAME/woodpecker-ci-demo:latest"


