when:
  - event: [pull_request_closed,push]
    branch: main

steps:
  - name: build
    image: node:latest
    commands:
      - echo "Installing dependencies..."
      - npm --prefix app install 
  - name: test
    image: node:latest
    commands:
      - echo "Running jest tests..."
      - npm --prefix app test
