when:
  - event: [push]
    branch: main

steps:
  - name: print commit message
    image: busybox
    commands:
      - echo "commit msg - ${CI_COMMIT_MESSAGE}"
      - env

  - name: build
    image: node:latest
    commands:
      - echo "Installing dependencies..."
      - npm --prefix app install 
  - name: test
    image: node:latest
    commands:
      - echo "Running jest tests..."
      - npm --prefix app test

  - name: build-and-push
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: docker.io/${CI_REPO_OWNER}/woodpecker-ci-demo
      dockerfile: app/Dockerfile
      context: app
      platforms: linux/amd64,linux/arm64/v8
      tag: "${CI_PIPELINE_NUMBER}"
      username:
        from_secret: docker-username
      password:
        from_secret: docker-password

  - name: Update deployment.yaml
    image: alpine
    commands:
      - apk add yq
      - yq eval '.spec.template.spec.containers[0].image = "${CI_REPO_OWNER}/woodpecker-ci-demo:${CI_PIPELINE_NUMBER}"' -i app/k8/deployment.yaml
      - rm -rf app/node_modules


  - name: push commit
    image: appleboy/drone-git-push
    settings:
      branch: ${CI_COMMIT_BRANCH}
      remote: ${CI_REPO_CLONE_SSH_URL}
      commit_message: "[CI SKIP] bumping deployment version"
      force: true
      commit: true
      ssh_key:
        from_secret: github_key 


