services:
  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "--url=direct-mammal-equal.ngrok-free.app"
      - "http://host.docker.internal:8000"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - 4040:4040

  woodpecker-server:
    image: woodpeckerci/woodpecker-server:latest
    ports:
      - 8000:8000
    volumes:
      - woodpecker-server-data:/var/lib/woodpecker/
    env_file:
      - .env
    # environment:
    #   - WOODPECKER_OPEN=true
    #   - WOODPECKER_HOST=${WOODPECKER_HOST}
    #   - WOODPECKER_GITHUB=true
    #   - WOODPECKER_GITHUB_CLIENT=${WOODPECKER_GITHUB_CLIENT}
    #   - WOODPECKER_GITHUB_SECRET=${WOODPECKER_GITHUB_SECRET}
    #   - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:latest
    command: agent
    restart: always
    depends_on:
      - woodpecker-server
    volumes:
      - woodpecker-agent-config:/etc/woodpecker
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    # environment:
    #   - WOODPECKER_SERVER=woodpecker-server:9000
    #   - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}

volumes:
  woodpecker-server-data:
  woodpecker-agent-config: