apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
        - name: my-node-app
          image: prateekjoshi2013/woodpecker-ci-demo:152
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: my-node-app-service
spec:
  selector:
    app: my-node-app
  ports:
    - protocol: TCP
      port: 80 # Exposing port 80 externally
      targetPort: 3000 # Internal port on the container
  type: LoadBalancer
  template:
    spec:
      containers:
        - image: prateekjoshi2013/woodpecker-ci-demo:152
